<a href="https://colab.research.google.com/github/les1smore/DATA606-Capstone-Project/blob/main/1_Data_Cleaning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Loding data and necessary libraries

In [ ]:
from google.colab import drive
drive.mount('/content/gdrive/')

Mounted at /content/gdrive/


In [ ]:
import pandas as pd
import numpy as np
import seaborn as sns
sns.set_style('darkgrid')

In [ ]:
Data_2015 = pd.read_csv('/content/gdrive/Shareddrives/Data_606_Capstone_Project/Project_Files/2015.csv')

# Data Cleaning

In [ ]:
Data_2015.shape

(441456, 330)

In [ ]:
#check that the data by loading
Data_2015.head()

_STATE  FMONTH        IDATE IMONTH   IDAY    IYEAR  DISPCODE         SEQNO  \
0     1.0     1.0  b'01292015'  b'01'  b'29'  b'2015'    1200.0  2.015000e+09   
1     1.0     1.0  b'01202015'  b'01'  b'20'  b'2015'    1100.0  2.015000e+09   
2     1.0     1.0  b'02012015'  b'02'  b'01'  b'2015'    1200.0  2.015000e+09   
3     1.0     1.0  b'01142015'  b'01'  b'14'  b'2015'    1100.0  2.015000e+09   
4     1.0     1.0  b'01142015'  b'01'  b'14'  b'2015'    1100.0  2.015000e+09   

           _PSU  CTELENUM  ...  _PAREC1  _PASTAE1  _LMTACT1  _LMTWRK1  \
0  2.015000e+09       1.0  ...      4.0       2.0       1.0       1.0   
1  2.015000e+09       1.0  ...      2.0       2.0       3.0       3.0   
2  2.015000e+09       1.0  ...      9.0       9.0       9.0       9.0   
3  2.015000e+09       1.0  ...      4.0       2.0       1.0       1.0   
4  2.015000e+09       1.0  ...      4.0       2.0       1.0       1.0   

   _LMTSCL1  _RFSEAT2  _RFSEAT3  _FLSHOT6  _PNEUMO2  _AIDTST3  
0       1.0       1.0       1.0       NaN       NaN       1.0  
1       4.0       2.0       2.0       NaN       NaN       2.0  
2       9.0       9.0       9.0       9.0       9.0       NaN  
3       1.0       1.0       1.0       NaN       NaN       9.0  
4       1.0       1.0       1.0       NaN       NaN       1.0  

[5 rows x 330 columns]

In [ ]:
Data_2015.describe()

_STATE         FMONTH       DISPCODE         SEQNO  \
count  441456.000000  441456.000000  441456.000000  4.414560e+05   
mean       29.968715       6.359676    1115.040457  2.015005e+09   
std        16.034710       3.487131      35.746794  4.113443e+03   
min         1.000000       1.000000    1100.000000  2.015000e+09   
25%        19.000000       3.000000    1100.000000  2.015002e+09   
50%        29.000000       6.000000    1100.000000  2.015004e+09   
75%        44.000000       9.000000    1100.000000  2.015007e+09   
max        72.000000      12.000000    1200.000000  2.015023e+09   

               _PSU  CTELENUM       PVTRESD1  COLGHOUS  STATERES  \
count  4.414560e+05  254645.0  254645.000000      45.0  254643.0   
mean   2.015005e+09       1.0       1.000177       1.0       1.0   
std    4.113443e+03       0.0       0.013292       0.0       0.0   
min    2.015000e+09       1.0       1.000000       1.0       1.0   
25%    2.015002e+09       1.0       1.000000       1.0       1.0   
50%    2.015004e+09       1.0       1.000000       1.0       1.0   
75%    2.015007e+09       1.0       1.000000       1.0       1.0   
max    2.015023e+09       1.0       2.000000       1.0       1.0   

            CELLFON3  ...        _PAREC1       _PASTAE1       _LMTACT1  \
count  254646.000000  ...  441456.000000  441456.000000  438657.000000   
mean        1.545133  ...       3.494124       2.742695       2.716879   
std         0.497960  ...       2.398322       2.449676       1.324145   
min         1.000000  ...       1.000000       1.000000       1.000000   
25%         1.000000  ...       2.000000       2.000000       2.000000   
50%         2.000000  ...       3.000000       2.000000       3.000000   
75%         2.000000  ...       4.000000       2.000000       3.000000   
max         2.000000  ...       9.000000       9.000000       9.000000   

            _LMTWRK1       _LMTSCL1       _RFSEAT2       _RFSEAT3  \
count  438657.000000  438657.000000  441456.000000  441456.000000   
mean        2.815149       3.652717       1.824624       1.887028   
std         1.356101       1.266730       2.360812       2.351387   
min         1.000000       1.000000       1.000000       1.000000   
25%         2.000000       3.000000       1.000000       1.000000   
50%         3.000000       4.000000       1.000000       1.000000   
75%         3.000000       4.000000       1.000000       1.000000   
max         9.000000       9.000000       9.000000       9.000000   

            _FLSHOT6       _PNEUMO2       _AIDTST3  
count  157954.000000  157954.000000  398069.000000  
mean        2.290705       2.412259       1.970156  
std         2.518086       2.778032       1.441119  
min         1.000000       1.000000       1.000000  
25%         1.000000       1.000000       1.000000  
50%         1.000000       1.000000       2.000000  
75%         2.000000       2.000000       2.000000  
max         9.000000       9.000000       9.000000  

[8 rows x 323 columns]

In [ ]:
#Lots of null values unbalanced data set

In [ ]:
# select specific columns for now just using 2015 can do for all years
Data_2015_selected = Data_2015[['_RFHLTH',
                                '_HCVU651',
                                '_RFHYPE5',
                                '_RFCHOL',
                                '_MICHD',
                                '_ASTHMS1',
                                '_DRDXAR1',
                                '_RACE',
                                '_BMI5CAT',
                                '_RFBMI5',
                                '_EDUCAG',
                                '_INCOMG',
                                '_SMOKER3', 
                                '_RFDRHV5',
                                '_FRTLT1', 
                                '_VEGLT1', 
                                '_PACAT1', 
                                '_PAINDX1',
                                '_PASTRNG',
                                'PHYSHLTH',
                                'MENTHLTH', 
                                'MEDCOST',
                                'CHECKUP1', 
                                'BPMEDS',
                                'CHCSCNCR', 
                                'CHCOCNCR',
                                'CHCCOPD1', 
                                'ADDEPEV2', 
                                'CHCKIDNY',
                                'DIABETE3',
                                'PREDIAB1', 
                                'INSULIN', 
                                'VICTRCT4',
                                'VIGLUMA2',
                                'VIMACDG2', 
                                'CIMEMLOS',
                                'DRADVISE', 
                                'ASNOSLEP',
                                'ADSLEEP', 
                                'SEX',
                                '_AGEG5YR']]

In [ ]:
Data_2015_selected.shape

(441456, 41)

In [ ]:
Data_2015_selected.head()

_RFHLTH  _HCVU651  _RFHYPE5  _RFCHOL  _MICHD  _ASTHMS1  _DRDXAR1  _RACE  \
0      2.0       1.0       2.0      2.0     2.0       1.0       1.0    1.0   
1      1.0       2.0       1.0      1.0     2.0       3.0       2.0    1.0   
2      2.0       9.0       1.0      2.0     NaN       3.0       1.0    1.0   
3      2.0       1.0       2.0      2.0     2.0       3.0       1.0    1.0   
4      2.0       1.0       1.0      1.0     2.0       3.0       1.0    1.0   

   _BMI5CAT  _RFBMI5  ...  INSULIN  VICTRCT4  VIGLUMA2  VIMACDG2  CIMEMLOS  \
0       4.0      2.0  ...      NaN       NaN       NaN       NaN       NaN   
1       3.0      2.0  ...      NaN       NaN       NaN       NaN       1.0   
2       2.0      1.0  ...      NaN       NaN       NaN       NaN       NaN   
3       3.0      2.0  ...      NaN       NaN       NaN       NaN       1.0   
4       2.0      1.0  ...      NaN       NaN       NaN       NaN       2.0   

   DRADVISE  ASNOSLEP  ADSLEEP  SEX  _AGEG5YR  
0       NaN       NaN      NaN  2.0       9.0  
1       2.0       NaN      NaN  2.0       7.0  
2       NaN       NaN      NaN  2.0      11.0  
3       2.0       NaN      NaN  2.0       9.0  
4       2.0       NaN      NaN  2.0       9.0  

[5 rows x 41 columns]

In [ ]:
Data_2015_selected.dtypes

_RFHLTH     float64
_HCVU651    float64
_RFHYPE5    float64
_RFCHOL     float64
_MICHD      float64
_ASTHMS1    float64
_DRDXAR1    float64
_RACE       float64
_BMI5CAT    float64
_RFBMI5     float64
_EDUCAG     float64
_INCOMG     float64
_SMOKER3    float64
_RFDRHV5    float64
_FRTLT1     float64
_VEGLT1     float64
_PACAT1     float64
_PAINDX1    float64
_PASTRNG    float64
PHYSHLTH    float64
MENTHLTH    float64
MEDCOST     float64
CHECKUP1    float64
BPMEDS      float64
CHCSCNCR    float64
CHCOCNCR    float64
CHCCOPD1    float64
ADDEPEV2    float64
CHCKIDNY    float64
DIABETE3    float64
PREDIAB1    float64
INSULIN     float64
VICTRCT4    float64
VIGLUMA2    float64
VIMACDG2    float64
CIMEMLOS    float64
DRADVISE    float64
ASNOSLEP    float64
ADSLEEP     float64
SEX         float64
_AGEG5YR    float64
dtype: object

## Clean the columns 

In [ ]:
#1 _RFHLTH Adults with good or better health
# Change all 2 to 0 (2= Fair/Poor heath)
# remove all dont knows and missing 9 health status is an important maker in this study
Data_2015_selected['_RFHLTH'] = Data_2015_selected['_RFHLTH'].replace({2:0})
Data_2015_selected = Data_2015_selected[Data_2015_selected._RFHLTH != 9]
Data_2015_selected._RFHLTH.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


array([0., 1.])

In [ ]:

#2 _HCVU651 Respondents aged 18-64 who have any form of health care coverage
# Change all 2 to 0 (2= does not have health coverage)
# Cannot remove don't know/missing because other important health Q's may have been answered by these individuals
Data_2015_selected['_HCVU651'] = Data_2015_selected['_HCVU651'].replace({2:0})
Data_2015_selected._HCVU651.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  after removing the cwd from sys.path.


array([1., 0., 9.])

In [ ]:
#3 _RFHYPE5 Adults who have been told they have high blood pressure by a doctor, nurse, or other health professional
#Change 1 to 0 so it represetnts No high blood pressure and 2 to 1 so it represents high blood pressure
Data_2015_selected['_RFHYPE5'] = Data_2015_selected['_RFHYPE5'].replace({1:0, 2:1})
Data_2015_selected = Data_2015_selected[Data_2015_selected._RFHYPE5 != 9]
Data_2015_selected._RFHYPE5.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([1., 0.])

In [ ]:
#4 _RFCHOL Adults who have had their cholesterol checked and have been told by a doctor, nurse, or other health professional that it was high
#Change 1 to 0 so it represetnts No high Cholesterol and 2 to 1 so it represents high cholesterol 
Data_2015_selected['_RFCHOL'] = Data_2015_selected['_RFCHOL'].replace({1:0, 2:1})
Data_2015_selected = Data_2015_selected[Data_2015_selected._RFCHOL != 9]
Data_2015_selected._RFCHOL.unique()

array([ 1.,  0., nan])

In [ ]:
#5 _MICHD Respondents that have ever reported having coronary heart disease (CHD) or myocardial infarction (MI)
#Change 2 to 0 so it represetnts No CHD/MI 
Data_2015_selected['_MICHD'] = Data_2015_selected['_MICHD'].replace({2:0})
Data_2015_selected._MICHD.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([ 0., nan,  1.])

In [ ]:
#6 _ASTHMS1 Computed asthma status 
# Change 3 to 0 leave 1 as current and 2 as former 
Data_2015_selected['_ASTHMS1'] = Data_2015_selected['_ASTHMS1'].replace({3:0})
Data_2015_selected = Data_2015_selected[Data_2015_selected._ASTHMS1 != 9]
Data_2015_selected._ASTHMS1.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([1., 0., 2.])

In [ ]:
#7 _DRDXAR1 Respondents who have had a doctor diagnose them as having some form of arthritis
#Change 2 to 0 so it represetnts No arthritis 
Data_2015_selected['_DRDXAR1'] = Data_2015_selected['_DRDXAR1'].replace({2:0})
Data_2015_selected._DRDXAR1.unique()

array([ 1.,  0., nan])

In [ ]:
#8 _RACE Race/ethnicity categories keep everything the same 1-7 remove 'don't know category; 
Data_2015_selected = Data_2015_selected[Data_2015_selected._RACE != 9]
Data_2015_selected._RACE.unique()

array([1., 7., 2., 3., 6., 8., 4., 5.])

In [ ]:
#10 _BMI5CAT Four-categories of Body Mass Index (BMI) 1= under weight, 2= normal weight, 3= overweight, 4= obese
# remove don't know blank 
Data_2015_selected = Data_2015_selected[Data_2015_selected._BMI5CAT != 9999]
Data_2015_selected._BMI5CAT.unique()

array([ 4.,  3.,  2.,  1., nan])

In [ ]:
#11 _RFBMI5 Adults who have a body mass index greater than 25.00 (Overweight or Obese)
#Change 1 to 0 so it represetnts No high BMI and 2 to 1 so it represents high BMI
Data_2015_selected['_RFBMI5'] = Data_2015_selected['_RFBMI5'].replace({1:0, 2:1})
Data_2015_selected = Data_2015_selected[Data_2015_selected._RFBMI5 != 9]
Data_2015_selected._RFBMI5.unique()

array([1., 0.])

In [ ]:
#12 _EDUCAG  Level of education completed
# remove don't know missing 
Data_2015_selected = Data_2015_selected[Data_2015_selected._EDUCAG != 9]
Data_2015_selected._EDUCAG.unique()

array([2., 4., 3., 1.])

In [ ]:
#13 _INCOMG Income Categories
# remove don't know missing 
Data_2015_selected = Data_2015_selected[Data_2015_selected._INCOMG != 9]
Data_2015_selected._INCOMG.unique()

array([2., 1., 5., 4., 3.])

In [ ]:
#14 _SMOKER3 Adults who are current smokers
#Change 1 to 0 so it represetnts Don't currently smoke  and 2 to 1 so it represents current smokers 
Data_2015_selected['_SMOKER3'] = Data_2015_selected['_SMOKER3'].replace({1:0, 2:1})
Data_2015_selected = Data_2015_selected[Data_2015_selected._SMOKER3 != 9]
Data_2015_selected._SMOKER3.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([3., 0., 4., 1.])

In [ ]:
# 15 _RFDRHV5 Heavy drinkers (adult men having more than 14 drinks per week and adult women having more than 7 drinks per week)
#Change 1 to 0 so it represetnts NO  and 2 to 1 so it represents YES
Data_2015_selected['_RFDRHV5'] = Data_2015_selected['_RFDRHV5'].replace({1:0, 2:1})
Data_2015_selected._RFDRHV5.unique()

array([0., 9., 1.])

In [ ]:
#16 _FRTLT1 Consume Fruit 1 or more times per day
#Change 2 to 0 so it represents no
Data_2015_selected['_FRTLT1'] = Data_2015_selected['_FRTLT1'].replace({2:0})
Data_2015_selected._FRTLT1.unique()

array([0., 1., 9.])

In [ ]:
#17 _VEGLT1 Consume Vegetables 1 or more times per day
#Change 2 to 0 so it represents no
Data_2015_selected['_VEGLT1'] = Data_2015_selected['_VEGLT1'].replace({2:0})
Data_2015_selected._VEGLT1.unique()

array([1., 0., 9.])

In [ ]:
#18 _PACAT1 Physical Activity Categories leave as is 

In [ ]:
#19 _PAINDX1 Physical Activity Index met or did not meet physical activity demands 
#Change 2 to 0 so it represents no
Data_2015_selected['_PAINDX1'] = Data_2015_selected['_PAINDX1'].replace({2:0})
Data_2015_selected._PAINDX1.unique()

array([0., 1., 9.])

In [ ]:
#20 _PASTRNG Muscle Strengthening Recommendation
#Change 2 to 0 so it represents did not meet muscle strenghening reccomendations
Data_2015_selected['_PASTRNG'] = Data_2015_selected['_PASTRNG'].replace({2:0})
Data_2015_selected._PASTRNG.unique()

array([0., 9., 1.])

In [ ]:
#21 PHYSHLTH Now thinking about your physical health, which includes physical illness and injury, for how many days during the past 30 days was your physical health not good?
# Changee 88 to 0 to represent no days of poor health 
Data_2015_selected['PHYSHLTH'] = Data_2015_selected['PHYSHLTH'].replace({88:0})
Data_2015_selected.PHYSHLTH.unique()

array([15.,  0., 30.,  8.,  2., 14., 99.,  6., 28.,  7., 77.,  1., 20.,
        3., 10.,  5., 17.,  4., 19., 25., 12., 27., 21., 22., 29., 24.,
        9., 16., 18., 23., 13., 11., 26.])

In [ ]:
#22 MENTHLTH Now thinking about your mental health, which includes stress, depression, and problems with emotions, for how many days during the past 30 days was your mental health not good?
# Changee 88 to 0 to represent no days of poor health 
Data_2015_selected['MENTHLTH'] = Data_2015_selected['MENTHLTH'].replace({88:0})
Data_2015_selected.MENTHLTH.unique()

array([18.,  0., 30.,  3., 99.,  2.,  5., 15., 10.,  1.,  6.,  7., 20.,
       77., 25., 29.,  4.,  8., 21., 14., 26., 16., 28., 11., 17., 12.,
       23., 24., 13., 27., 22., 19.,  9.])

In [ ]:
#23 MEDCOST  Was there a time in the past 12 months when you needed to see a doctor but could not because of cost?
# Changee 2 to 0 to represent no 
Data_2015_selected['MEDCOST'] = Data_2015_selected['MEDCOST'].replace({2:0})
Data_2015_selected.MEDCOST.unique()

array([ 0.,  1.,  7.,  9., nan])

In [ ]:
#24 CHECKUP1 About how long has it been since you last visited a doctor for a routine checkup?
# Changee 8 to 0 to represent never 
Data_2015_selected['CHECKUP1'] = Data_2015_selected['CHECKUP1'].replace({8:0})
Data_2015_selected.CHECKUP1.unique()

array([ 1.,  4.,  3.,  2.,  0.,  7.,  9., nan])

In [ ]:
#25 BPMEDS Are you currently taking medicine for your high blood pressure?
# Changee 2 to 0 to represent no 
Data_2015_selected['BPMEDS'] = Data_2015_selected['BPMEDS'].replace({2:0})
Data_2015_selected.BPMEDS.unique()

array([ 1., nan,  0.,  7.,  9.])

In [ ]:
#26 CHCSCNCR (Ever told) you had skin cancer?
# Changee 2 to 0 to represent no 
Data_2015_selected['CHCSCNCR'] = Data_2015_selected['CHCSCNCR'].replace({2:0})
Data_2015_selected.CHCSCNCR.unique()

array([0., 1., 7., 9.])

In [ ]:
#27 CHCOCNCR (Ever told) you had any other types of cancer?
# Changee 2 to 0 to represent no 
Data_2015_selected['CHCOCNCR'] = Data_2015_selected['CHCOCNCR'].replace({2:0})
Data_2015_selected.CHCOCNCR.unique()

array([0., 1., 7., 9.])

In [ ]:
#28 CHCCOPD1 (Ever told) you have Chronic Obstructive Pulmonary Disease or COPD, emphysema or chronic bronchitis?
# Changee 2 to 0 to represent no 
Data_2015_selected['CHCCOPD1'] = Data_2015_selected['CHCCOPD1'].replace({2:0})
Data_2015_selected.CHCCOPD1.unique()

array([1., 0., 7., 9.])

In [ ]:
#29 ADDEPEV2 (Ever told) you that you have a depressive disorder, including depression, major depression, dysthymia, or minor depression?
# Changee 2 to 0 to represent no 
Data_2015_selected['ADDEPEV2'] = Data_2015_selected['ADDEPEV2'].replace({2:0})
Data_2015_selected.ADDEPEV2.unique()

array([1., 0., 9., 7.])

In [ ]:
#30 CHCKIDNY (Ever told) you have kidney disease? Do NOT include kidney stones, bladder infection or incontinence.(Incontinence is not being able to control urine flow.)
# Changee 2 to 0 to represent no 
Data_2015_selected['CHCKIDNY'] = Data_2015_selected['CHCKIDNY'].replace({2:0})
Data_2015_selected.CHCKIDNY.unique()

array([0., 7., 1., 9.])

In [ ]:
#31 DIABETE3 Ever told) you have diabetes (If "Yes" and respondent is female, ask "Was this only when you were pregnant?". If Respondent says pre-diabetes or borderline diabetes, use response code 4.)
# Change to 0 is for no diabetes or only during pregnancy, 1 is for pre-diabetes or borderline diabetes, 2 is for yes diabetes
# Remove all 7 (dont knows)
# Remove all 9 (refused)
Data_2015_selected['DIABETE3'] = Data_2015_selected['DIABETE3'].replace({2:0, 3:0, 1:2, 4:1})
Data_2015_selected = Data_2015_selected[Data_2015_selected.DIABETE3 != 7]
Data_2015_selected = Data_2015_selected[Data_2015_selected.DIABETE3 != 9]
Data_2015_selected.DIABETE3.unique()

array([ 0.,  2.,  1., nan])

In [ ]:
#32 PREDIAB1 Have you ever been told by a doctor or other health professional that you have pre-diabetes or borderline diabetes? (If “Yes” and respondent is female, ask: “Was this only when you were pregnant?”)
# Changee 3 to 0 to represent no 
Data_2015_selected['PREDIAB1'] = Data_2015_selected['PREDIAB1'].replace({3:0})
Data_2015_selected.PREDIAB1.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([ 0., nan,  1.,  2.,  7.,  9.])

In [ ]:
#33 INSULIN Are you now taking insulin?
# Changee 2 to 0 to represent no 
Data_2015_selected['INSULIN'] = Data_2015_selected['INSULIN'].replace({2:0})
Data_2015_selected.INSULIN.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  0.,  1.,  9.])

In [ ]:
#34 VICTRCT4 Have you been told by an eye doctor or other health care professional that you NOW have cataracts?
# Changee 3 to 0 to represent no 
Data_2015_selected['VICTRCT4'] = Data_2015_selected['VICTRCT4'].replace({3:0})
Data_2015_selected.VICTRCT4.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  0.,  1.,  2.,  7.])

In [ ]:
#35 VIGLUMA2 Have you EVER been told by an eye doctor or other health care professional that you had glaucoma?
# Changee 2 to 0 to represent no 
Data_2015_selected['VIGLUMA2'] = Data_2015_selected['VIGLUMA2'].replace({2:0})
Data_2015_selected.VIGLUMA2.unique()


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  0.,  1.,  7.])

In [ ]:
#36 VIMACDG2 Have you EVER been told by an eye doctor or other health care professional that you had age-related macular degeneration?
# Changee 2 to 0 to represent no 
Data_2015_selected['VIMACDG2'] = Data_2015_selected['VIMACDG2'].replace({2:0})
Data_2015_selected.VIMACDG2.unique()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  0.,  1.,  7.])

In [ ]:
#37 CIMEMLOS During the past 12 months, have you experienced confusion or memory loss that is happening more often or is getting worse?
# Changee 2 to 0 to represent no 
Data_2015_selected['CIMEMLOS'] = Data_2015_selected['CIMEMLOS'].replace({2:0})
Data_2015_selected.CIMEMLOS.unique()


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  This is separate from the ipykernel package so we can avoid doing imports until


array([nan,  1.,  0.,  7.,  9.])

In [ ]:
#38 DRADVISE Are you currently watching or reducing your sodium or salt intake?
# Changee 2 to 0 to represent no 
Data_2015_selected['DRADVISE'] = Data_2015_selected['DRADVISE'].replace({2:0})
Data_2015_selected.DRADVISE.unique()


array([nan,  0.,  1.,  9.,  7.])

In [ ]:
#39 ASNOSLEP During the past 30 days, how many days did symptoms of asthma make it difficult for you to stay asleep? Would you say
# Changee 8 to 0 to represent no 
Data_2015_selected['ASNOSLEP'] = Data_2015_selected['ASNOSLEP'].replace({8:0})
Data_2015_selected.ASNOSLEP.unique()


array([nan,  0.,  1.,  2.,  3.,  5.,  4.,  7.])

In [ ]:
#40 ADSLEEP Over the last 2 weeks, how many days have you had trouble falling asleep or staying asleep or sleeping too much?
# Changee 88 to 0 to represent no 
Data_2015_selected['ADSLEEP'] = Data_2015_selected['ADSLEEP'].replace({88:0})
Data_2015_selected.ADSLEEP.unique()

array([nan,  0.,  7., 14.,  3.,  5.,  4.,  2., 77.,  8., 12., 10.,  9.,
        1.,  6., 13., 11., 99.])

In [ ]:
#41 SEX Indicate sex of respondent leave as is

In [ ]:
#42 AGEG5YR
# already ordinal. 1 is 18-24 all the way up to 13 wis 80 and older. 5 year increments.
# remove 14 because it is don't know or missing
Data_2015_selected = Data_2015_selected[Data_2015_selected._AGEG5YR != 14]
Data_2015_selected._AGEG5YR.unique()

array([ 9.,  7., 11., 13., 10., 12.,  8.,  4.,  6.,  2.,  3.,  5.,  1.])

In [ ]:
Data_2015_selected.shape

(325844, 41)

In [ ]:
Data_2015_selected.head()

_RFHLTH  _HCVU651  _RFHYPE5  _RFCHOL  _MICHD  _ASTHMS1  _DRDXAR1  _RACE  \
0      0.0       1.0       1.0      1.0     0.0       1.0       1.0    1.0   
1      1.0       0.0       0.0      0.0     0.0       0.0       0.0    1.0   
3      0.0       1.0       1.0      1.0     0.0       0.0       1.0    1.0   
5      1.0       9.0       1.0      0.0     0.0       0.0       1.0    1.0   
6      1.0       9.0       1.0      1.0     0.0       0.0       0.0    7.0   

   _BMI5CAT  _RFBMI5  ...  INSULIN  VICTRCT4  VIGLUMA2  VIMACDG2  CIMEMLOS  \
0       4.0      1.0  ...      NaN       NaN       NaN       NaN       NaN   
1       3.0      1.0  ...      NaN       NaN       NaN       NaN       1.0   
3       3.0      1.0  ...      NaN       NaN       NaN       NaN       1.0   
5       3.0      1.0  ...      NaN       NaN       NaN       NaN       0.0   
6       2.0      0.0  ...      NaN       NaN       NaN       NaN       0.0   

   DRADVISE  ASNOSLEP  ADSLEEP  SEX  _AGEG5YR  
0       NaN       NaN      NaN  2.0       9.0  
1       0.0       NaN      NaN  2.0       7.0  
3       0.0       NaN      NaN  2.0       9.0  
5       0.0       NaN      NaN  2.0      11.0  
6       1.0       NaN      NaN  2.0      11.0  

[5 rows x 41 columns]

In [ ]:
#Check Class Sizes of the heart disease column
Data_2015_selected.groupby(['DIABETE3']).size()

DIABETE3
0.0    278341
1.0      5568
2.0     41932
dtype: int64

In [ ]:
#Rename the columns to make them more readable
Data_2015 = Data_2015_selected.rename(columns = {'_RFHLTH':'Good Health',
                                                 '_HCVU651':'Health Coverage' , 
                                                 '_RFHYPE5':'High Blood Pressure',
                                                 '_RFCHOL':'High Cholesterol',
                                                 '_MICHD':'CHD-MI', 
                                                 '_ASTHMS1':'Asthma Status', 
                                                 '_DRDXAR1': 'Diagnosed Arthritis',
                                                 '_RACE':'Race/Ethnicity',
                                                 '_BMI5CAT':'BMI Category',
                                                 '_RFBMI5':'Overweight/Obese',
                                                 '_EDUCAG':'Education Level',
                                                 '_INCOMG':'Income Category',
                                                 '_SMOKER3':'Smoker Status',
                                                 '_RFDRHV5':'Heavy Drinker',
                                                 '_FRTLT1':'Consume Fruit', 
                                                 '_VEGLT1':'Consume Veggie',
                                                 '_PACAT1':'Physical Activity Categories',
                                                 '_PAINDX1':'Aerobic Reccomendations',
                                                 '_PASTRNG':'Muscle Strengthening Recommendation',
                                                 'PHYSHLTH':'Good Physical Health',
                                                 'MENTHLTH':'Good Mental Health', 
                                                 'MEDCOST':'High Cost of Medical',
                                                 'CHECKUP1':'Routine Check-up', 
                                                 'BPMEDS':'Taking BP Meds',
                                                 'CHCSCNCR':'Skin Cancer', 
                                                 'CHCOCNCR':'Other Cancer',
                                                 'CHCCOPD1':'Chronic Obstructive Pulmonary Disease', 
                                                 'ADDEPEV2':'Depressive Disorder', 
                                                 'CHCKIDNY':'Kidney Disease',
                                                 'DIABETE3':'Have_Diabetes',
                                                 'PREDIAB1':'Pre-diabetic', 
                                                 'INSULIN':'Taking Insulin', 
                                                 'VICTRCT4':'Have Cateracts',
                                                 'VIGLUMA2':'Glaucoma',
                                                 'VIMACDG2':'macular degeneration', 
                                                 'CIMEMLOS':'Memory Loss',
                                                 'DRADVISE':'Watching sodium', 
                                                 'ASNOSLEP':'Sleep Disordered Breathing',
                                                 'ADSLEEP':'Trouble sleeping', 
                                                 'SEX':'Sex',
                                                 '_AGEG5YR':'Age'})

In [ ]:
Data_2015.head()

Good Health  Health Coverage  High Blood Pressure  High Cholesterol  \
0          0.0              1.0                  1.0               1.0   
1          1.0              0.0                  0.0               0.0   
3          0.0              1.0                  1.0               1.0   
5          1.0              9.0                  1.0               0.0   
6          1.0              9.0                  1.0               1.0   

   CHD-MI  Asthma Status  Diagnosed Arthritis  Race/Ethnicity  BMI Category  \
0     0.0            1.0                  1.0             1.0           4.0   
1     0.0            0.0                  0.0             1.0           3.0   
3     0.0            0.0                  1.0             1.0           3.0   
5     0.0            0.0                  1.0             1.0           3.0   
6     0.0            0.0                  0.0             7.0           2.0   

   Overweight/Obese  ...  Taking Insulin  Have Cateracts  Glaucoma  \
0               1.0  ...             NaN             NaN       NaN   
1               1.0  ...             NaN             NaN       NaN   
3               1.0  ...             NaN             NaN       NaN   
5               1.0  ...             NaN             NaN       NaN   
6               0.0  ...             NaN             NaN       NaN   

   macular degeneration  Memory Loss  Watching sodium  \
0                   NaN          NaN              NaN   
1                   NaN          1.0              0.0   
3                   NaN          1.0              0.0   
5                   NaN          0.0              0.0   
6                   NaN          0.0              1.0   

   Sleep Disordered Breathing  Trouble sleeping  Sex   Age  
0                         NaN               NaN  2.0   9.0  
1                         NaN               NaN  2.0   7.0  
3                         NaN               NaN  2.0   9.0  
5                         NaN               NaN  2.0  11.0  
6                         NaN               NaN  2.0  11.0  

[5 rows x 41 columns]

In [ ]:
Data_2015.shape

(325844, 41)

In [ ]:
#Check how many respondents have no diabetes, prediabetes or diabetes. Note the class imbalance!
Data_2015.groupby(['Have_Diabetes']).size()

Have_Diabetes
0.0    278341
1.0      5568
2.0     41932
dtype: int64

In [ ]:
Data_2015.to_csv('./Clean_data.csv', sep=",", index=False)

In [ ]:
# Change prediabetic to non-diabetic to make the data set binary for ease
Data_2015B = Data_2015
Data_2015B['Have_Diabetes']= Data_2015B['Have_Diabetes'].replace({1:0})
Data_2015B['Have_Diabetes']= Data_2015B['Have_Diabetes'].replace({2:1})
Data_2015B.Have_Diabetes.unique()

In [ ]:
Data_2015B.groupby('Have_Diabetes').size()

In [ ]:
Data_2015B.to_csv('diabetes_B.csv', sep=",", index=False)